helmOperator:
    create: true
    chartsSyncInterval: 1m
    configureRepositories:
      enable: true
registry:
  acr:
    enabled: true
git:
  url: git@github.com:hmcts/flux-demo
  pollInterval: 1m